name: Build Package 
on: [push, pull_request]
jobs:
  test_git_actions1:
    name: test seleniem job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event on ${{runner.os}}"
      - name: checkout source code 
        uses: actions/checkout@v6.0.1
      - run: echo " this repo is ${{ github.repository}} "
      - name: run a script file from repo  file 
        run : sh ./run.sh
        shell: bash
    
      
  test_git_actions1:
    name: test seleniem job2
    runs-on: ubuntu-latest
    needs: test_git_actions1           # to add dependency on first job 
    steps:
    - run: echo "this is second job "
